[package]
name = "rust_lib_frb_example_rust_ui_todo_list"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "staticlib"]

[dependencies]
flutter_rust_bridge = { path = "../../frb_rust" }
